### ISSUE TITLE
[BUG]: Not able to save Position (1.20.6)

### ISSUE THREAD

**Issue by XCraftTM** [JSander1808/Positionator#5]
I have just recently installed the Plugin on my Survival Server running Paper 1.20.6 and when i want to use /pos YOURPOS, then it opens the GUI but i am unable to select if i want to save it in public or private, i am just able to grab the Items from the GUI and put them back if i wanted to...
![javaw_qJSOXABVhP](https://github.com/JSander1808/Positionator/assets/72396660/8125a9f2-ca5c-4f51-bd9d-a34c5c9caafc)

**Comment by XCraftTM** [comment]
Update: It has an Issue with the German Translation, once i switched back to English it worked just fine!

**Comment by JSander1808** [comment]
I have fixed the problem in the latest version. ([Download here](https://github.com/JSander1808/Positionator/releases))

Thank you for your feedback and for using the Positionator.
